In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_excel('homeprices.xlsx')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
df.bedrooms.fillna(df.bedrooms.mean(),inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.2   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
model = LinearRegression()
model.fit(df.drop('price', axis='columns'), df.price)

LinearRegression()

In [7]:
model.coef_

array([  116.66950551, 18756.28806982, -3675.75111708])

In [8]:
model.intercept_

231586.00639409182

**Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old**

In [10]:
model.predict([[3000, 3, 40]])

array([490833.34243748])

**Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old**

In [12]:
model.predict([[2500, 4, 5]])

array([579906.16685223])